### ISSUE TITLE
Generation of a hierarchical population (inheritances)

### ISSUE THREAD

**Issue by rmejean** [ANRGenstar/genstar.gamaplugin#3]
Hi,

Is it now possible to use the GENSTAR plugin to generate a population structured by inheritance relationships between classes? For example, to generate households and related individuals? Maybe with the operator `associate_population_agents` ? I don't know what it's for.

Thank you for your answers,
Romain

**Comment by chapuisk** [comment]
Hi @rmejean ,
Unfortunately, there is no valid algorithm in the Gen* library to do so. I am working on several options, but not any ones will be available soon in the plugin ... most of classical IPU or HIPF algorithms are really stringent in term of sample attributes (must contains weights of records or individual records into household records). I explore several alternative ideas (e.g. hierarchical mixture -- [here](https://www.sciencedirect.com/science/article/pii/S0191261517308615) -- and RJMCMC with colleagues from ISC-Pif) but I have not been able to find enough time to implement them in Gen* (because of course there is no open source free implementations in Java). But with a bit of help it might be possible to do something in a reasonable amount of time ;)
Best,
Kevin

**Comment by rmejean** [comment]
Hi Kevin,
Thank you for your answer, that's interesting! Unfortunately, I don't think I have the skills to be useful to you in these implementations... neither in programming nor in pop generation... 
I'll manage differently for my model, I'm lucky to have a "household identifier" in my pop data!

Best,
Romain
