### ISSUE TITLE
About localize_on_geometries

### ISSUE THREAD

**Issue by rmejean** [ANRGenstar/genstar.gamaplugin#4]
Hi,

I would like to know more about how the operator `localize_on_geometries` works: can a geometry be used several times to locate an agent ? Or does it consider that a geometry already used to spatialize an agent can no longer be re-used?
Perhaps it would be interesting to add this possibility: do not allow the same geometry to be used multiple times to locate an agent or allow it.
For example, allow the generation of several individuals in the same building (in the case of a city with high pop density) or not: have only one maximum agent per building (in the case of a rural area, low density).

Thank you in advance for the answer!

Best regards,
Romain

**Comment by chapuisk** [comment]
Hey @rmejean ,

Yes a spatial entities can contain several agent. And there is no satisfactory way to ensure that there is only one agent per spatial entity; because, then it might happen that an agent cannot be located anywhere.

For the enhancement you asked for, It happens that the feature is already coded in the API. I've add it to the plugin, but you'll have to test for bugs ;)

So you can define a spatial distribution based on a capacity constraints using the operator ``add_capacity_distribution``. You can use it for two purpose: 

1. Define a general capacity constraints for every spatial entity: e.g. if you do ``add_capacity_distribution(1)`` you'll have only one agent per spatial entities, IF there is enough of them; otherwise you'll have the minimum number of agent per spatial entities
2. The capacity is based on a feature of each spatial entity: e.g. if you do ``add_capacity_distribution("name_of_capacity_feature")`` the localization will look at the variable "name_of_capacity_feature" in each spatial entities to define a maximum number of agent to locate in.

I've tried to use it in ``models/tests/localize_in_building.gaml`` !

Best,
Kevin

**Comment by rmejean** [comment]
Hi @chapuisk,

Great! Thank you for your answer and for this plugin update, this feature is very useful! I will try it and come back here to report bugs if there are any. ;)

Best,
Romain

**Comment by rmejean** [comment]
Re- @chapuisk,

I tried the functionality. It works well in the first case (for every spatial entity, e.g. `add_capacity_distribution(1)`), but not in the second (based on a feature of each spatial entity), for which I get a nil value error detected... but **I don't have any null value** in my `"name_of_capacity_feature"` attribute.

![error2](https://user-images.githubusercontent.com/22102206/67220428-1767e780-f42a-11e9-9367-7c6f97eabc31.PNG)

Best,
Romain

**Comment by chapuisk** [comment]
Hey @rmejean ,
It seems that Genstar is not able to find the attribute called ``name_of_capacity_feature`` in your nests. It means that in the file hog_gen.nest (which is a vector or raster file) each spatial entities must have an attribute called that way, and that this attribute should be a number. 
I pushed a new error message for this; can you try again with the advice above ?
Best,
Kevin

**Comment by rmejean** [comment]
Hi @chapuisk,
Sorry, but I don't understand what nests are. **Where should the attribute `name_of_capacity_feature` be placed?** I put it in the shapefile I use to locate agents (my "buildings" layer contains a "capacity_max" attribute in its dbf). But this way, it doesn't work. The capacity distribution is not defined at the level of the shape layer used to locate?
The new error message runs very well. ;)

Thanks,
Romain

**Comment by chapuisk** [comment]
Hi @rmejean ,

I think there is a misunderstanding: The string ``name_of_capacity_feature`` is not an attribute, rather in your case it should be replace by ``capacity_max`` . Hence, Genstar is able to find the proper attribute in your shape file. In this case, the nest seems to be a building, i.e. the spatial entity an agent is bind to as its "home place". In those spatial entity, if you have such capacity feature, you might use it with ``hog_gen add_capacity_distribution "capacity_max"``
If there is still bugs after that, we might go MP ;)

PS: I also add a density based distribution, with the ``add_density_distribution`` operator.

Best,
Kevin
